import { IEventSystem } from "../../ts-common/events";
import { View } from "../../ts-common/view";
import { Exporter } from "./helpers/Export";
import { Selection } from "./helpers/Selection";
import { ShapesCollection } from "./ShapesCollection";
import { Toolbar } from "./Toolbar";
import { DataEvents, DiagramEvents, ICoords, IDiagram, IDiagramConfig, IBaseShape, SelectionEvents, IDiagramEventHandlersMap, ICustomShapeParam, IAutoPlacement, TreeDir, IBaseCoords } from "./types";
import { EditorEvents, IEditor } from "./helpers/Editor";
import { CellManager, CellManagerEvents, ICellManagerHandlersMap } from "./helpers/CellManager";
export declare class Diagram extends View implements IDiagram {
    version: string;
    config: IDiagramConfig;
    events: IEventSystem<DataEvents | SelectionEvents | DiagramEvents | EditorEvents | CellManagerEvents, IDiagramEventHandlersMap | ICellManagerHandlersMap>;
    data: ShapesCollection;
    selection: Selection;
    export: Exporter;
    toolbar: Toolbar;
    flowShapes: any;
    editor: IEditor;
    cellManager: CellManager;
    private _htmlevents;
    private _diagramSize;
    private _active;
    private _orgTypes;
    private _menu;
    constructor(container: HTMLElement | any, config?: IDiagramConfig);
    addShape(type: string, parameters: ICustomShapeParam): void;
    locate(event: Event): IBaseShape;
    collapseItem(id: string, dir?: TreeDir): void;
    expandItem(id: string, dir?: TreeDir): void;
    getScrollState(): ICoords;
    scrollTo(x: number, y: number): void;
    showItem(id: string, dir?: TreeDir): void;
    autoPlace(config?: IAutoPlacement): void;
    getCurrentCoordinates(event: MouseEvent): IBaseCoords;
    destructor(): void;
    protected _set_defaults(): void;
    protected _init_events(): void;
    protected _init_struct(): void;
    protected _render(vm: any): any;
    private _getContent;
    private _getPoint;
}
